<a href="https://colab.research.google.com/github/Aanchal0102/Data_analyst_ineternship/blob/main/Pandas_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas Series
A Pandas Series is like a column in a table.

It is a one-dimensional array holding data of any type.

In [1]:
import pandas as pd

In [2]:
# Series Method

series = pd.Series([1, 7, 2, 8, 5])

print(series)

0    1
1    7
2    2
3    8
4    5
dtype: int64

In [3]:
# Series Method with Index

series = pd.Series([1, 7, 2, 8, 5], index = ["a", "b", "c","d","e"])

print(series)

a    1
b    7
c    2
d    8
e    5
dtype: int64

In [4]:
# Accessing Series elements

print(series[2])
print(series["c"])

2
2

<ipython-input-4-32d1d9a8ed40>:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(series[2])

# Pandas DataFrame

A Data frame is a two-dimensional data structure, i.e., data is aligned in a tabular fashion in rows and columns.

In [5]:
# DataFrame Method on list

data = pd.DataFrame([1,2,3,4,5])
print(data)

   0
0  1
1  2
2  3
3  4
4  5

In [6]:
# DataFrame using Dictionary

data = pd.DataFrame({'Name':['Tom', 'Jack', 'Steve', 'Ricky','Sam','Will','Root'],
                     'Age':[28,34,29,42,17,17,45]})
data.head(10)

    Name  Age
0    Tom   28
1   Jack   34
2  Steve   29
3  Ricky   42
4    Sam   17
5   Will   17
6   Root   45

In [7]:
# DataFrame with Index

data = pd.DataFrame({'Name':['Tom', 'Jack', 'Steve', 'Ricky','Sam','Will','Root'],
                     'Age':[28,34,29,42,17,17,45]}, index=['C1','C2','C3','C4','C5','C6','C7'])
data.head(10)

     Name  Age
C1    Tom   28
C2   Jack   34
C3  Steve   29
C4  Ricky   42
C5    Sam   17
C6   Will   17
C7   Root   45

In [8]:
# Column Selection

# data['Name']
data['Age']

C1    28
C2    34
C3    29
C4    42
C5    17
C6    17
C7    45
Name: Age, dtype: int64

In [9]:
data.head(10)

     Name  Age
C1    Tom   28
C2   Jack   34
C3  Steve   29
C4  Ricky   42
C5    Sam   17
C6   Will   17
C7   Root   45

In [10]:
# Row Selection

# data.loc['C4','Age']
data.iloc[3,0]

'Ricky'

# Pandas Concatenation

It is used to concatenate pandas objects along a particular axis with optional set logic along the other axes.

In [11]:
names = pd.DataFrame({'Name':['Tom', 'Jack', 'Steve', 'Ricky','Sam','Will','Root']})
ages = pd.DataFrame({'Age':[28,34,29,42,17,17,45]})

In [12]:
names2 = pd.DataFrame({'Name':['Joe', 'Pope', 'Buttler', 'Ben','James','Cook']})

In [13]:
names2

      Name
0      Joe
1     Pope
2  Buttler
3      Ben
4    James
5     Cook

In [14]:
ages

   Age
0   28
1   34
2   29
3   42
4   17
5   17
6   45

In [15]:
pd.concat([names, ages], axis = 1)                     # Concatenation

    Name  Age
0    Tom   28
1   Jack   34
2  Steve   29
3  Ricky   42
4    Sam   17
5   Will   17
6   Root   45

In [16]:
pd.concat([names, names2])                # Concatenation

      Name
0      Tom
1     Jack
2    Steve
3    Ricky
4      Sam
5     Will
6     Root
0      Joe
1     Pope
2  Buttler
3      Ben
4    James
5     Cook

# Pandas Indexing

loc() , iloc(), Filtering methods

In [17]:
data

     Name  Age
C1    Tom   28
C2   Jack   34
C3  Steve   29
C4  Ricky   42
C5    Sam   17
C6   Will   17
C7   Root   45

In [18]:
# data['Name']
data[['Name','Age']]

     Name  Age
C1    Tom   28
C2   Jack   34
C3  Steve   29
C4  Ricky   42
C5    Sam   17
C6   Will   17
C7   Root   45

In [19]:
data[data['Age'] <= 18][['Name']]

    Name
C5   Sam
C6  Will

In [20]:
data[data['Age'] <= 18][['Name']]

    Name
C5   Sam
C6  Will

In [21]:
data[data['Age'] > 40]

     Name  Age
C4  Ricky   42
C7   Root   45

In [22]:
data

     Name  Age
C1    Tom   28
C2   Jack   34
C3  Steve   29
C4  Ricky   42
C5    Sam   17
C6   Will   17
C7   Root   45

In [23]:
print(data.loc['C2','Name'])
print(data.iloc[1,0])

Jack
Jack